"""Compatibility wrapper for the default concrete instance prompt assets."""

from instantiation.amphoreus.prompts import (
    AMPHOREUS_WORLD_PROMPT_PATH,
    CHARACTERS_PROMPTS_ROOT,
    CYRENE_CARD_PROMPT_PATH,
    CYRENE_HEARTBEAT_PROMPT_PATH,
    CYRENE_PROMPTS_ROOT,
    CYRENE_SOUL_PROMPT_PATH,
    CYRENE_USER_BRIDGE_PROMPT_PATH,
    PROMPTS_ROOT,
    SYSTEM_PROMPTS_ROOT,
    WORLD_ACTIVITIES_PROMPTS_ROOT,
    WORLD_LORE_PROMPTS_ROOT,
    WORLD_PLACES_PROMPTS_ROOT,
    WORLD_PROMPTS_ROOT,
    build_cyrene_system_prompt,
    load_amphoreus_world_prompt,
    load_character_prompt,
    load_prompt_text,
    load_system_prompt,
    load_world_lore_prompt,
    load_world_place_prompt,
)

__all__ = [
    "PROMPTS_ROOT",
    "SYSTEM_PROMPTS_ROOT",
    "CHARACTERS_PROMPTS_ROOT",
    "WORLD_PROMPTS_ROOT",
    "WORLD_LORE_PROMPTS_ROOT",
    "WORLD_PLACES_PROMPTS_ROOT",
    "WORLD_ACTIVITIES_PROMPTS_ROOT",
    "AMPHOREUS_WORLD_PROMPT_PATH",
    "CYRENE_PROMPTS_ROOT",
    "CYRENE_SOUL_PROMPT_PATH",
    "CYRENE_CARD_PROMPT_PATH",
    "CYRENE_USER_BRIDGE_PROMPT_PATH",
    "CYRENE_HEARTBEAT_PROMPT_PATH",
    "load_prompt_text",
    "load_system_prompt",
    "load_character_prompt",
    "load_world_lore_prompt",
    "load_world_place_prompt",
    "load_amphoreus_world_prompt",
    "build_cyrene_system_prompt",
]
